<?xml version="1.0" encoding="UTF-8"? >
<definitions name="CustomerService" targetNamespace="http://test.webservice.transformatech.com/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://test.webservice.transformatech.com/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <documentation>
    <appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="CustomerPortBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </appinfo>
  </documentation>
  <types>
    <xsd:schema>
      <xsd:import namespace="http://test.webservice.transformatech.com/" schemaLocation="CustomerService_schema1.xsd"/>
    </xsd:schema>
  </types>
  <message name="insertCustomer">
    <part element="tns:insertCustomer" name="parameters"/>
  </message>
  <message name="getCustomerResponse">
    <part element="tns:getCustomerResponse" name="parameters"/>
  </message>
  <message name="insertCustomerResponse">
    <part element="tns:insertCustomerResponse" name="parameters"/>
  </message>
  <message name="getCustomer">
    <part element="tns:getCustomer" name="parameters"/>
  </message>
  <portType name="Customer">
    <operation name="getCustomer">
      <input message="tns:getCustomer" wsam:Action="http://test.webservice.transformatech.com/Customer/getCustomerRequest"/>
      <output message="tns:getCustomerResponse" wsam:Action="http://test.webservice.transformatech.com/Customer/getCustomerResponse"/>
    </operation>
    <operation name="insertCustomer">
      <input message="tns:insertCustomer" wsam:Action="http://test.webservice.transformatech.com/Customer/insertCustomerRequest"/>
      <output message="tns:insertCustomerResponse" wsam:Action="http://test.webservice.transformatech.com/Customer/insertCustomerResponse"/>
    </operation>
  </portType>
  <binding name="CustomerPortBinding" type="tns:Customer">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="getCustomer">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
    <operation name="insertCustomer">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="CustomerService">
    <port binding="tns:CustomerPortBinding" name="CustomerPort">
      <soap:address location="http://localhost:9080/Customer/CustomerService"/>
    </port>
  </service>
</definitions>